name: Compile
on: [push, pull_request]
jobs:
  compile:
    name: Byte-compile (Emacs ${{ matrix.emacs-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version:
          - '29.1'
          - '29.2'
          - '29.3'
          - '29.4'
          - '30.1'
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      - uses: extractions/setup-just@v2
      - run: just compile
